services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_UERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: whatever